name: minty
description: "A fresh take on education."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.4.0
  go_router: ^10.1.2
  dartz: ^0.10.1
  get_it: ^7.6.0
  equatable: ^2.0.5
  path_provider: ^2.1.5
  share_plus: ^11.1.0
  file_picker: ^10.3.2
  flutter_form_builder: ^10.2.0
  form_builder_validators: ^11.2.0
  reorderables: ^0.6.0
  split_button: ^0.1.0
  uuid: ^4.4.0
  intl: 0.20.2
  pdf: ^3.11.3
  image_picker: ^1.0.7
  printing: ^5.11.1
  top_snackbar_flutter: ^3.3.0
  spell_check_on_client: ^1.0.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/minty_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  windows:
    generate: true
    image_path: "path/to/image.png"
    icon_size: 48 # min:48, max:256, default: 48

flutter:
  uses-material-design: true
  assets:
    - assets/times.ttf
    - assets/timesbd.ttf
    - assets/timesbi.ttf
    - assets/timesi.ttf
    - assets/en_words.txt
    - assets/florence_academy.png
  fonts:
    - family: AnonymicePro
      fonts:
        - asset: assets/AnonymiceProNerdFontMono-Regular.ttf
        - asset: assets/AnonymiceProNerdFontMono-Bold.ttf
          weight: 700
        - asset: assets/AnonymiceProNerdFontMono-Italic.ttf
          style: italic
    - family: Outfit
      fonts:
        - asset: assets/Outfit-Regular.otf
        - asset: assets/Outfit-Bold.otf
          weight: 700
        - asset: assets/Outfit-Light.otf
          weight: 300
    - family: TimesNewRoman
      fonts:
        - asset: assets/times.ttf
        - asset: assets/timesbd.ttf
          weight: 700
        - asset: assets/timesi.ttf
          style: italic
        - asset: assets/timesbi.ttf
          weight: 700
          style: italic
