name: teachers_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  go_router: ^10.1.2
  dartz: ^0.10.1
  get_it: ^7.6.0
  equatable: ^2.0.5
  docx_template: ^0.4.0
  path_provider: ^2.1.5
  share_plus: ^11.1.0
  file_picker: ^10.3.2
  flutter_form_builder: ^10.2.0
  form_builder_validators: ^11.2.0
  reorderables: ^0.6.0
  split_button: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/template.docx
  fonts:
    - family: AnonymicePro
      fonts:
        - asset: assets/AnonymiceProNerdFontMono-Regular.ttf
        - asset: assets/AnonymiceProNerdFontMono-Bold.ttf
          weight: 700
        - asset: assets/AnonymiceProNerdFontMono-Italic.ttf
          style: italic
    - family: Outfit
      fonts:
        - asset: assets/Outfit-Regular.otf
        - asset: assets/Outfit-Bold.otf
          weight: 700
        - asset: assets/Outfit-Light.otf
          weight: 300